services:
  redis:
    image: redis:latest
    container_name: sandbox-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  celery-worker:
    build:
      context: ./celery-worker
      dockerfile: ../Dockerfile-worker
    container_name: sandbox_celery
    devices:
      - /dev/kvm:/dev/kvm
    privileged: true
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./celery-worker:/app
    depends_on:
      - redis

volumes:
  redis_data: