services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  celery-worker:
    build: .
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  redis_data: