[project]
name = "celery-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "redis>=5.2.1",
]

[project.optional-dependencies]
dev = ["pytest", "black"]
celery = ["kombu", "redis"]
